---
mysql_packages:
  - mariadb-server
  - python3-PyMySQL
mysql_packages_remove:
  - mysql
  - mysql-common
mysql_service_name: mariadb
mysql_socket: /var/lib/mysql/mysql.sock
mysql_config_path: /etc/my.cnf.d/wordpress.cnf
